apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy-alpine:v1.18.2
        imagePullPolicy: Always
        args: ["-l", "debug", "--local-address-ip-version", "v4", "-c", "/run/envoy/envoy.yaml", "--base-id", "1"]
        volumeMounts:
        - name: envoy-config
          mountPath: "/run/envoy"
          readOnly: true 
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true          
      - name: mongo-client
        imagePullPolicy: IfNotPresent
        image: mongoclient/mongoclient
        ports:
        - containerPort: 3000
      volumes:
      - name: envoy-config
        configMap:
          name: client-envoy
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: DirectoryOrCreate
