node:
  id: "mongo-client"
  cluster: "demo-tcpcluster-spire"
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: tcp
          cluster: mongo-backend
  clusters:
  - name: spire_agent
    connect_timeout: 1s
    typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: {}
    load_assignment:  
      cluster_name: spire_agent
      endpoints:  
      - lb_endpoints: 
        - endpoint: 
            address:  
              pipe: 
                path: /run/spire/sockets/agent.sock
  - name: mongo-backend
    connect_timeout: 1s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: mongo-backend
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: mongo-envoy
                port_value: 10100
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        common_tls_context:
          tls_certificate_sds_secret_configs:
            - name: "spiffe://envoy.spire-test.com/ns/default/sa/default/mongo-client"
              sds_config:
                api_config_source:
                  api_type: GRPC
                  grpc_services:
                    envoy_grpc:
                      cluster_name: spire_agent
                  transport_api_version: V3
                resource_api_version: V3
          combined_validation_context:
            default_validation_context:
              match_subject_alt_names:
                exact: "spiffe://envoy.spire-test.com/ns/default/sa/default/mongo-backend"
            validation_context_sds_secret_config:
              name: "spiffe://envoy.spire-test.com"
              sds_config:
                api_config_source:
                  api_type: GRPC
                  grpc_services:
                    envoy_grpc:
                      cluster_name: spire_agent
                  transport_api_version: V3
                resource_api_version: V3
          tls_params:
            ecdh_curves:
              - X25519:P-256:P-521:P-384
