kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: spire-mongo-pvc
   annotations:
     volume.beta.kubernetes.io/storage-class: spire-gp2
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 2Gi
